-- Runs once, on first Postgres container initialization only (Docker only
-- executes files in /docker-entrypoint-initdb.d when the data directory is
-- empty). Alembic (backend/alembic) owns all actual schema + extension
-- management (including `CREATE EXTENSION vector`, in the initial
-- migration) — this file is intentionally left empty of DDL so there is
-- exactly one source of truth for schema state.
