"""series hierarchy, rule evidence and quantification, extraction cache

Revision ID: 65218d424d73
Revises: c1aa9750ea72
Create Date: 2026-09-02 09:53:00.820291

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65218d424d73'
down_revision: str | None = 'c1aa9750ea72'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', 'extractor_name', 'prompt_version', name='uq_extraction_cache_key')
    )
    op.create_index(op.f('ix_extraction_cache_content_hash'), 'extraction_cache', ['content_hash'], unique=False)
    op.create_index(op.f('ix_extraction_cache_extractor_name'), 'extraction_cache', ['extractor_name'], unique=False)
    op.create_table('series',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('creator_name', sa.String(length=255), nullable=False),
    sa.Column('series_name', sa.String(length=255), nullable=False),
    sa.Column('youtube_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_creator_name'), 'series', ['creator_name'], unique=False)
    op.create_index(op.f('ix_series_project_id'), 'series', ['project_id'], unique=False)
    op.create_index(op.f('ix_series_youtube_playlist_id'), 'series', ['youtube_playlist_id'], unique=False)
    op.create_table('rule_quantifications',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('proposals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('user_defined_alternative', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('selected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_quantifications_rule_id'), 'rule_quantifications', ['rule_id'], unique=False)
    op.add_column('concept_relations', sa.Column('label', sa.String(length=128), nullable=True))
    op.add_column(
        'concepts',
        sa.Column(
            'instrument_tags',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
    )
    op.add_column('rules', sa.Column('series_id', sa.UUID(), nullable=True))
    op.add_column(
        'rules',
        sa.Column(
            'evidence_type',
            sa.Enum('EXPLICIT', 'IMPLIED', 'DISCRETIONARY', 'USER_DEFINED', 'AI_ASSUMPTION', name='ruleevidencetype', native_enum=False, length=32),
            nullable=False,
            server_default='EXPLICIT',
        ),
    )
    op.add_column('rules', sa.Column('quantifiability', sa.Enum('FULLY_QUANTIFIABLE', 'PARTIALLY_QUANTIFIABLE', 'DISCRETIONARY', name='quantifiability', native_enum=False, length=32), nullable=True))
    op.add_column(
        'rules',
        sa.Column(
            'instrument_tags',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default='[]',
        ),
    )
    op.create_index(op.f('ix_rules_evidence_type'), 'rules', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_rules_series_id'), 'rules', ['series_id'], unique=False)
    op.create_foreign_key(None, 'rules', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.add_column('transcript_chunks', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transcript_chunks_content_hash'), 'transcript_chunks', ['content_hash'], unique=False)
    op.add_column('videos', sa.Column('series_id', sa.UUID(), nullable=True))
    op.add_column('videos', sa.Column('position_in_series', sa.Integer(), nullable=True))
    op.add_column(
        'videos', sa.Column('is_manual_import', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.create_index(op.f('ix_videos_series_id'), 'videos', ['series_id'], unique=False)
    op.create_foreign_key(None, 'videos', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_index(op.f('ix_videos_series_id'), table_name='videos')
    op.drop_column('videos', 'is_manual_import')
    op.drop_column('videos', 'position_in_series')
    op.drop_column('videos', 'series_id')
    op.drop_index(op.f('ix_transcript_chunks_content_hash'), table_name='transcript_chunks')
    op.drop_column('transcript_chunks', 'content_hash')
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_index(op.f('ix_rules_series_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_evidence_type'), table_name='rules')
    op.drop_column('rules', 'instrument_tags')
    op.drop_column('rules', 'quantifiability')
    op.drop_column('rules', 'evidence_type')
    op.drop_column('rules', 'series_id')
    op.drop_column('concepts', 'instrument_tags')
    op.drop_column('concept_relations', 'label')
    op.drop_index(op.f('ix_rule_quantifications_rule_id'), table_name='rule_quantifications')
    op.drop_table('rule_quantifications')
    op.drop_index(op.f('ix_series_youtube_playlist_id'), table_name='series')
    op.drop_index(op.f('ix_series_project_id'), table_name='series')
    op.drop_index(op.f('ix_series_creator_name'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_extraction_cache_extractor_name'), table_name='extraction_cache')
    op.drop_index(op.f('ix_extraction_cache_content_hash'), table_name='extraction_cache')
    op.drop_table('extraction_cache')
    # ### end Alembic commands ###
