"""Pine Script v6 generator (Module 9).

Renders a `//@version=6` `strategy()` script from a `StrategySpecification`.
Structured fields (session, stop method, target method, position sizing,
direction permissions, max trades/day) become real, executable Pine logic.
Free-text fields without a recognized `machine_readable_rule.type` become
inert placeholder conditions with a TODO comment quoting the source rule —
see `app/codegen/conditions.py` for why this is not silently "made to
work" instead.

This output has not been run through TradingView's own Pine compiler (this
service has no such compiler available) — treat it as a structured,
traceable starting point that must be opened in the Pine Editor and
verified before use, not as verified-correct code.
"""

from __future__ import annotations

from datetime import UTC, datetime

from app.codegen.conditions import render_condition
from app.codegen.spec_embedding import embed_spec_comment
from app.schemas.strategy_spec import StrategySpecification

_PINE_COMMENT = "//"


def _header(spec: StrategySpecification, version_label: str) -> str:
    now = datetime.now(UTC).isoformat()
    return f"""// Generated by StrategyForge AI — do not hand-edit the metadata block below.
// Strategy: {spec.strategy_name}
// Strategy Version: {version_label}
// Generation Date: {now}
//
// This script is a structured translation of extracted trading education
// content. It is NOT a claim that this strategy is profitable or safe to
// trade, and it has not been verified against TradingView's Pine compiler.
// Review every TODO below before use.
{embed_spec_comment(spec, _PINE_COMMENT)}"""


def generate_pine_script(spec: StrategySpecification, version_label: str) -> str:
    bias = render_condition(
        spec.bias_rule or "", spec.bias_condition, spec.field_sources.get("bias_rule", [])
    )
    setup = render_condition(
        spec.setup_rule or "", spec.setup_condition, spec.field_sources.get("setup_rule", [])
    )
    confirmation = render_condition(
        spec.confirmation_rule or "",
        spec.confirmation_condition,
        spec.field_sources.get("confirmation_rule", []),
    )
    entry = render_condition(
        spec.entry_rule or "", spec.entry_condition, spec.field_sources.get("entry_rule", [])
    )

    allow_long = spec.allow_long if spec.allow_long is not None else False
    allow_short = spec.allow_short if spec.allow_short is not None else False
    risk_pct = (
        spec.position_sizing.value
        if spec.position_sizing and spec.position_sizing.method == "RISK_PERCENT"
        else 1.0
    )
    max_trades = spec.max_trades_per_day if spec.max_trades_per_day is not None else 0

    session_block = "inSession = true // No SESSION rule was extracted/approved — runs all bars."
    if spec.session:
        s = spec.session
        session_str = f"{s.start_time.replace(':', '')}-{s.end_time.replace(':', '')}"
        session_block = (
            f'sessionSpec = "{session_str}"\n'
            f'inSession = not na(time(timeframe.period, sessionSpec, "{s.timezone}"))'
        )

    stop_block = (
        "// No STOP_LOSS rule was compiled — stopDistance left at na (no stop will be placed)."
    )
    stop_distance_expr = "na"
    if spec.stop_loss:
        sl = spec.stop_loss
        if sl.method == "FIXED_POINTS" and sl.value is not None:
            stop_distance_expr = str(sl.value)
        elif sl.method == "FIXED_PERCENT" and sl.value is not None:
            stop_distance_expr = f"close * {sl.value / 100.0}"
        elif sl.method == "ATR_MULTIPLE" and sl.value is not None:
            stop_distance_expr = f"ta.atr(14) * {sl.value}"
        else:
            stop_distance_expr = "na"
        stop_block = (
            f"// Stop method: {sl.method} — {sl.description}\nstopDistance = {stop_distance_expr}"
        )

    target_block = "// No TAKE_PROFIT rule was compiled — targetDistance left at na."
    if spec.take_profit:
        tp = spec.take_profit
        if tp.method == "R_MULTIPLE" and tp.value is not None:
            target_expr = f"stopDistance * {tp.value}"
        elif tp.method == "FIXED_POINTS" and tp.value is not None:
            target_expr = str(tp.value)
        elif tp.method == "FIXED_PERCENT" and tp.value is not None:
            target_expr = f"close * {tp.value / 100.0}"
        elif tp.method == "ATR_MULTIPLE" and tp.value is not None:
            target_expr = f"ta.atr(14) * {tp.value}"
        else:
            target_expr = "na"
        target_block = (
            f"// Target method: {tp.method} — {tp.description}\ntargetDistance = {target_expr}"
        )
    else:
        target_block += "\ntargetDistance = na"

    no_trade_comments = (
        "\n".join(
            f"// NO_TRADE_CONDITION (not auto-enforced — review): {c}"
            for c in spec.no_trade_conditions
        )
        or "// No NO_TRADE_CONDITIONS rules were compiled."
    )
    invalidation_comment = (
        f"// INVALIDATION rule (not auto-enforced as a hard exit — review): {spec.invalidation_rule}"
        if spec.invalidation_rule
        else "// No INVALIDATION rule was compiled."
    )

    body = f"""
//@version=6
{_header(spec, version_label)}

strategy(
     title="{spec.strategy_name}",
     overlay=true,
     initial_capital=10000,
     default_qty_type=strategy.percent_of_equity,
     default_qty_value=100,
     calc_on_every_tick=false,
     process_orders_on_close=true)

// --- Inputs -----------------------------------------------------------
allowLong = input.bool({str(allow_long).lower()}, "Allow long entries")
allowShort = input.bool({str(allow_short).lower()}, "Allow short entries")
riskPctInput = input.float({risk_pct}, "Risk % of equity per trade", minval=0.0)
maxTradesPerDayInput = input.int({max_trades}, "Max trades per day (0 = unlimited)", minval=0)

// --- Session filter -----------------------------------------------------
{session_block}

// --- Bias, setup, confirmation, entry conditions ------------------------
// Bias rule: {spec.bias_rule or "(none extracted)"}
biasCondition = {bias.pine}
// Setup rule: {spec.setup_rule or "(none extracted)"}
setupCondition = {setup.pine}
// Confirmation rule: {spec.confirmation_rule or "(none extracted)"}
confirmationCondition = {confirmation.pine}
// Entry trigger: {spec.entry_rule or "(none extracted)"}
entryTrigger = {entry.pine}

{invalidation_comment}
{no_trade_comments}

// --- Daily trade count guard --------------------------------------------
var int tradesToday = 0
var int lastTradeDay = na
today = dayofmonth(time)
if na(lastTradeDay) or today != lastTradeDay
    tradesToday := 0
    lastTradeDay := today

dailyLimitOk = maxTradesPerDayInput == 0 or tradesToday < maxTradesPerDayInput

// --- Risk / sizing --------------------------------------------------------
{stop_block}
{target_block}

longSignal = allowLong and inSession and dailyLimitOk and biasCondition and setupCondition and confirmationCondition and entryTrigger and strategy.position_size == 0
shortSignal = allowShort and inSession and dailyLimitOk and biasCondition and setupCondition and confirmationCondition and entryTrigger and strategy.position_size == 0

if longSignal
    tradesToday := tradesToday + 1
    strategy.entry("Long", strategy.long)
    if not na(stopDistance)
        strategy.exit("Long Exit", "Long", stop=close - stopDistance, limit=na(targetDistance) ? na : close + targetDistance)

if shortSignal
    tradesToday := tradesToday + 1
    strategy.entry("Short", strategy.short)
    if not na(stopDistance)
        strategy.exit("Short Exit", "Short", stop=close + stopDistance, limit=na(targetDistance) ? na : close - targetDistance)

// --- Plots / debugging markers -------------------------------------------
plotshape(longSignal, title="Long Signal", style=shape.triangleup, location=location.belowbar, color=color.green, size=size.tiny)
plotshape(shortSignal, title="Short Signal", style=shape.triangledown, location=location.abovebar, color=color.red, size=size.tiny)
plot(strategy.equity, title="Equity", display=display.data_window)
"""
    return body.strip() + "\n"
