"""Python strategy generator (Module 10).

Renders a standalone, dependency-light (pandas/numpy only) Python module
from the same `StrategySpecification` the Pine generator reads — see
`app/codegen/spec_embedding.py` for how the two are verified to encode the
identical spec. Like the Pine output, free-text rule fields without a
recognized `machine_readable_rule.type` render as an inert `False`
condition with a TODO, never a fabricated boolean expression.

The generated module exposes `generate_signals(df)`, which returns a
DataFrame of long/short entry signals plus stop/target distances per bar —
this is the same shape `app/backtesting/engine.py` consumes, so generated
code can be round-tripped straight into this service's own backtester.
"""

from __future__ import annotations

from datetime import UTC, datetime

from app.codegen.conditions import render_condition
from app.codegen.spec_embedding import embed_spec_comment
from app.schemas.strategy_spec import StrategySpecification

_PY_COMMENT = "#"

_HELPERS = """
def ema(series, length):
    return series.ewm(span=length, adjust=False).mean()


def sma(series, length):
    return series.rolling(length).mean()


def atr(high, low, close, length=14):
    prev_close = close.shift(1)
    tr = pd.concat(
        [high - low, (high - prev_close).abs(), (low - prev_close).abs()], axis=1
    ).max(axis=1)
    return tr.rolling(length).mean()


def session_vwap(high, low, close, volume, session_date):
    typical = (high + low + close) / 3.0
    pv = typical * volume
    grouped_pv = pv.groupby(session_date).cumsum()
    grouped_vol = volume.groupby(session_date).cumsum()
    return grouped_pv / grouped_vol.replace(0, pd.NA)
"""


def _header(spec: StrategySpecification, version_label: str) -> str:
    now = datetime.now(UTC).isoformat()
    return f'''"""Generated by StrategyForge AI — do not hand-edit the metadata block below.

Strategy: {spec.strategy_name}
Strategy Version: {version_label}
Generation Date: {now}

This module is a structured translation of extracted trading education
content. It is NOT a claim that this strategy is profitable or safe to
trade. Review every TODO before use.
"""
{embed_spec_comment(spec, _PY_COMMENT)}

from __future__ import annotations

import pandas as pd
'''


def generate_python_strategy(spec: StrategySpecification, version_label: str) -> str:
    bias = render_condition(
        spec.bias_rule or "", spec.bias_condition, spec.field_sources.get("bias_rule", [])
    )
    setup = render_condition(
        spec.setup_rule or "", spec.setup_condition, spec.field_sources.get("setup_rule", [])
    )
    confirmation = render_condition(
        spec.confirmation_rule or "",
        spec.confirmation_condition,
        spec.field_sources.get("confirmation_rule", []),
    )
    entry = render_condition(
        spec.entry_rule or "", spec.entry_condition, spec.field_sources.get("entry_rule", [])
    )

    allow_long = bool(spec.allow_long)
    allow_short = bool(spec.allow_short)
    risk_pct = (
        spec.position_sizing.value
        if spec.position_sizing and spec.position_sizing.method == "RISK_PERCENT"
        else None
    )
    max_trades = spec.max_trades_per_day

    session_filter = "in_session = pd.Series(True, index=df.index)  # No SESSION rule was compiled."
    if spec.session:
        s = spec.session
        session_filter = (
            f'local_time = df.index.tz_convert("{s.timezone}")\n'
            f"    minutes = local_time.hour * 60 + local_time.minute\n"
            f'    start_h, start_m = {int(s.start_time.split(":")[0])}, {int(s.start_time.split(":")[1])}\n'
            f'    end_h, end_m = {int(s.end_time.split(":")[0])}, {int(s.end_time.split(":")[1])}\n'
            f"    start_minutes, end_minutes = start_h * 60 + start_m, end_h * 60 + end_m\n"
            f"    weekday_ok = local_time.weekday.isin({spec.session.days_of_week})\n"
            f"    in_session = pd.Series(\n"
            f"        ((minutes >= start_minutes) & (minutes < end_minutes) & weekday_ok),\n"
            f"        index=df.index,\n"
            f"    )"
        )

    stop_expr = "None  # No STOP_LOSS rule was compiled"
    if spec.stop_loss:
        sl = spec.stop_loss
        if sl.method == "FIXED_POINTS" and sl.value is not None:
            stop_expr = f"pd.Series({sl.value}, index=df.index)"
        elif sl.method == "FIXED_PERCENT" and sl.value is not None:
            stop_expr = f"df['close'] * {sl.value / 100.0}"
        elif sl.method == "ATR_MULTIPLE" and sl.value is not None:
            stop_expr = f"atr(df['high'], df['low'], df['close'], 14) * {sl.value}"
        else:
            stop_expr = "None  # structure-based stop — not machine-translatable, review manually"

    target_expr = "None  # No TAKE_PROFIT rule was compiled"
    if spec.take_profit:
        tp = spec.take_profit
        if tp.method == "R_MULTIPLE" and tp.value is not None:
            target_expr = f"stop_distance * {tp.value} if stop_distance is not None else None"
        elif tp.method == "FIXED_POINTS" and tp.value is not None:
            target_expr = f"pd.Series({tp.value}, index=df.index)"
        elif tp.method == "FIXED_PERCENT" and tp.value is not None:
            target_expr = f"df['close'] * {tp.value / 100.0}"
        elif tp.method == "ATR_MULTIPLE" and tp.value is not None:
            target_expr = f"atr(df['high'], df['low'], df['close'], 14) * {tp.value}"
        else:
            target_expr = (
                "None  # structure-based target — not machine-translatable, review manually"
            )

    no_trade_comments = (
        "\n".join(
            f"    # NO_TRADE_CONDITION (not auto-enforced — review): {c}"
            for c in spec.no_trade_conditions
        )
        or "    # No NO_TRADE_CONDITIONS rules were compiled."
    )
    invalidation_comment = (
        f"    # INVALIDATION rule (not auto-enforced as a hard exit — review): {spec.invalidation_rule}"
        if spec.invalidation_rule
        else "    # No INVALIDATION rule was compiled."
    )

    body = f'''{_header(spec, version_label)}
{_HELPERS}

STRATEGY_NAME = {spec.strategy_name!r}
ALLOW_LONG = {allow_long!r}
ALLOW_SHORT = {allow_short!r}
RISK_PCT_PER_TRADE = {risk_pct!r}
MAX_TRADES_PER_DAY = {max_trades!r}


def generate_signals(df: pd.DataFrame) -> pd.DataFrame:
    """`df` must have a tz-aware DatetimeIndex and columns open/high/low/close/volume.

    Returns a DataFrame aligned to `df.index` with columns:
    long_entry, short_entry (bool), stop_distance, target_distance (float or NaN).
    """
    close, high, low, volume = df["close"], df["high"], df["low"], df["volume"]
    session_date = df.index.date
    vwap = session_vwap(high, low, close, volume, session_date)

    {session_filter}

    # Bias rule: {spec.bias_rule or "(none extracted)"}
    bias_condition = {bias.python}
    # Setup rule: {spec.setup_rule or "(none extracted)"}
    setup_condition = {setup.python}
    # Confirmation rule: {spec.confirmation_rule or "(none extracted)"}
    confirmation_condition = {confirmation.python}
    # Entry trigger: {spec.entry_rule or "(none extracted)"}
    entry_trigger = {entry.python}

{invalidation_comment}
{no_trade_comments}

    stop_distance = {stop_expr}
    target_distance = {target_expr}

    base_signal = in_session & bias_condition & setup_condition & confirmation_condition & entry_trigger
    long_entry = base_signal if ALLOW_LONG else pd.Series(False, index=df.index)
    short_entry = base_signal if ALLOW_SHORT else pd.Series(False, index=df.index)

    return pd.DataFrame(
        {{
            "long_entry": long_entry,
            "short_entry": short_entry,
            "stop_distance": stop_distance,
            "target_distance": target_distance,
        }},
        index=df.index,
    )
'''
    return body.strip() + "\n"
